### ISSUE TITLE
Tutorial and .gitignore

### ISSUE THREAD

**Issue by miohtama** [ethereum/populus#201]
* Populus Version: 1.4.0

### What was wrong?

Tutorial doesn't explain how to set up .gitignore for chain data files. This would be useful for newcomers to learn.

#### Cute Animal Picture

```
            o==+--
            |  |\ \
            |  | \ \    ____________________
            |   \ \ \   |                  |
            |    \ \ \  |  +------------+  |
            |     \ \ \ |  |     (__)   |  |
            |      \ \ \|  |     (oo)   |  |
            |       \ \ |  | o\  .\/.   |  |
            |        \ \|  | | \/    \  |  |
          /---\       \ |  +------------+  |
         /     \       \|                  |
         |     |        |                  |
         \     /        |                  |
          \---/         |                  |
                        |                  |
                     --------------------------
                    (                          )
                     --------------------------
 
                   Cow-struction worker.
```

**Comment by pipermerriam** [comment]
ooooooh, ascii animals!

**Comment by aj07** [comment]
Do i need to give little bit into about gitignore also ?

**Comment by itsN1X** [comment]
what's `chaindata`?
Sorry ( :

**Comment by aman935** [comment]
@miohtama Should I start working on this issue? Just need a thumbs up so I know that it is still relevant.

**Comment by miohtama** [comment]
@aman935 I think this has been addressed in some point over past two years

https://github.com/ethereum/populus/blob/master/.gitignore

You can see that chaindata files are in ignore.

**Comment by aman935** [comment]
Thanks for replying. I will move on to work with some other issue. 

Regards, 
Aman Singh

Sent from Mail for Windows 10
