### ISSUE TITLE
LLL: how to specify ABI?

### ISSUE THREAD

**Issue by veox** [ethereum/populus#400]
## What was wrong?

I'd like to allow Populus to compile and test LLL programs.

To do that, the compilation backend would likely need to provide the contract's ABI - mapping canonical function signatures and four-bytes.

However, this comes from a higher abstraction level than that at which LLL operates.

Below are some approaches that can be taken to achieve this, in no particular order.

### Macros

The [`Greeter.lll`](https://github.com/veox/populus/blob/e3e4adb12546cac7661643dc5b4dbc69c672e11d/tests/fixtures/Greeter.lll) example from PR #397 demonstrates _one_ possible approach, using some of @zigguratt's [`stdlib`](https://github.com/zigguratt/lll-stdlib).

So, we _could_, for example, extend the `function` macro to explicitly list the canonical signature; or add a special one that converts a canonical signature to four-bytes; and then make Populus parse the code, looking for this specific pattern. Something like (possibly invalid LLL):

``` lisp
(function (four-bytes "setGreeting(string)")
  (sstore current-greeting new-greeting))
```

I don't particularly like this approach, since it takes some of LLL's power away: putting the programmer in a rut of "public interface as a look-up table of four-byte sigs", and one particular macro trope that's tied to a specific library.

However, it does make for code that's otherwise legitimate LLL, and likely wouldn't be hard to support in other toolchains.

### Comments

Could instead add in-file comments with non-standard NatSpec-like syntax, e.g.:

``` lisp
;; @abi setGreeting(string)
(def 'new-greeting (calldataload 0x04))
(function set-greeting
  (sstore current-greeting new-greeting))

;; @abi greet()
(function greet
  (return (sload current-greeting)))
;; for compatibility with Greeter.sol
(function greeting ;; @abi greeting()
  (return (sload current-greeting)))
```

This is somewhat error-prone, but quite flexible.

### Additional file

All `.lll` files could require an accompanying `.lll.abi`. Perhaps the most "correct" approach, as far as Populus itself is concerned.

Also seems like the most flexible, although maybe uncomfortable due to the latter constantly getting out of sync. To mitigate, this can be combined with the previous approach; e.g. package `py-lll` could provide a tool to extract the comments, and put them in the respective `.lll.abi` file.

### Other approaches?

Your thoughts.

## P.S.

I could also bring this up "upstream", in `ethereum/solidity`, if it's thought to be more relevant there.

## Cute Animal Picture

"It's gonna be great, I can totally see it! (If I close my eyes.)" ([source](https://vulpeaspatiala.wordpress.com/) (says the search engine))

![fox with closed eyes and grin](https://vulpeaspatiala.files.wordpress.com/2012/10/adorable-animal-cute-fox-foxes-foxy-favim-com-62976.jpg)

**Comment by pipermerriam** [comment]
> All .lll files could require an accompanying .lll.abi. Perhaps the most "correct" approach, as far as Populus itself is concerned.

This one, while *cumbersome* is also the easiest to support and evolve.

**Comment by veox** [comment]
Was leaning towards it, too.

Will close issue with implementing PR.

**Comment by veox** [comment]
I've been using the "accompanying `.lll.abi` file" approach successfully (more or less) in PR #408.

This question has been answered, so closing.
