### ISSUE TITLE
bytes32 in event logs are awkward to test

### ISSUE THREAD

**Issue by jessebmiller** [ethereum/populus#410]
* Populus Version: 2.1.0
* OS: Linux (docker on a Mac)

### What was wrong?

I have a contract function that should take and log a bytes32 hash argument.

```
contract HashLogger {

    event HashReceived(bytes32 hash);

    function logHash(bytes32 hash) public {
        HashReceived(hash);
    }
}
```

In order to test that the logging is correct I make a hash,

```
test_hash = chain.web3.toBytes(hexstr=chain.web3.sha3(text="zk"))
```

and send the transaction.

```
txn_hash = HashLogger.transact().logHash(test_hash)
txn_receipt = chain.wait.for_receipt(txn_hash)
```

Then check that the hash is in the logs

```
filter = HashLogger.pastEvents("HashReceived")
logs = filter.get()
assert logs[0].args["hash"] == test_hash # fails
```

I expected that to match, but the data in `logs[0].args["hash"]` has been run through `eth_utils.force_obj_to_text` and so does not match the bytes I passed to the transaction.

My workaround is to import `force_obj_to_text` and use it with `test_hash`

```
assert logs[0].args["hash"] == force_obj_to_text(test_hash) # passes
```

I'd love something more intuitive.

I see that web3.py is going to deprecate `pastEvents` and `get` and it looks like moving to the recommended `eventFilter` and `get_all_entries` may solve this problem, but it looks like PopulusContract has not adopted them yet.

`filter = LogHasher.eventFilter("HashReceived")` gives the error `'PopulusContract' object has no attribute 'eventFilter'`

I'd be happy to try and get this working more cleanly if there is indeed work to be done.

#### Cute Animal Picture

![image](https://user-images.githubusercontent.com/471702/33916377-0792985a-df6e-11e7-9915-2f8aee4759e6.png)

**Comment by pipermerriam** [comment]
@jessebmiller I *think* that if you force web3 to a v4 beta version you can get access to the new events api.

In general, the usage of `force_obj_to_text` and any of the `eth_utils.force_*` functions is being deprecated.  See https://github.com/ethereum/eth-utils/issues/36

**Comment by jessebmiller** [comment]
Thanks, I'll check it out.
