### ISSUE TITLE
Outdated documentation

### ISSUE THREAD

**Issue by berndbohmeier** [ethereum/populus#413]
* Populus Version: 2.2.0
* OS: linux

### What was wrong?

The documentation on http://populus.readthedocs.io/en/v2.2.0/ is totally outdated and not useful anymore. The title says Populus 2.0.0-alpha.1 which is from on Feb 1.
I had to go to a lot of src code for:
 - deployment scripts
 - adding own chains like a parity chain

#### Cute Animal Picture

![](http://maxpixel.freegreatpicture.com/static/photo/1x/Hare-Sweet-Rabbit-Cute-Animal-Small-Hare-Pet-1436319.jpg)

**Comment by veox** [comment]
The title is misleading (broken). From the contents, I see it's definitely built recently, since it has the "Viper support" page.
