### ISSUE TITLE
please add a shebang line for init_chain.sh

### ISSUE THREAD

**Issue by introom** [ethereum/populus#434]
Failed to execute process './init_chain.sh'. Reason:
exec: Exec format error
The file './init_chain.sh' is marked as an executable but could not be run by the operating system.

**Comment by mandarvaze** [comment]
@introom which platform ? On macOS, `init_run.sh` works fine without a shebang line.

I guess a a shebang line won't hurt.

Can you confirm whether manually adding `#!/bin/sh` as a first line helps resolve your issue ?
If yes, I'll make the changes and submit a PR

**Comment by millennium-falcon42** [comment]
on debian sid.

adding shebang is more explicit, and should always be preferred.
e.g., #!/usr/bin/env bash

**Comment by carver** [comment]
Yup, a `sh` shebang sounds good (avoid an explicit `bash` dependency if we can)
