### ISSUE TITLE
 Plugin 'ethereum' could not be loaded when testing

### ISSUE THREAD

**Issue by robertmartin8** [ethereum/populus#446]
* OS: osx

### What was wrong?

While following the 'quickstart' on the documentation, I ran `py.test tests/`. I got the following error. 

```
pluggy.PluginValidationError: Plugin 'ethereum' could not be loaded: (eth-utils 0.8.1 (/anaconda/lib/python3.6/site-packages), Requirement.parse('eth-utils==0.7.*'), {'eth-abi'})!
```

I can probably just fix it by installing an older version of eth-utils, but I think the requirement should be updated. 

#### Cute Animal Picture

ʕ•ᴥ•ʔ

**Comment by mandarvaze** [comment]
@robertmartin8 I'm seeing same error.
Were you able to resolve this by installing `eth-utils == 0.7` ?

**Comment by KamnaJ** [comment]
I am getting same issue and installing eth-utils == 0.7 does not resolve it

**Comment by voith** [comment]
This issue will be resolved in https://github.com/ethereum/populus/pull/474

**Comment by veox** [comment]
PR #474 has been merged - is the issue resolved?

**Comment by voith** [comment]
This should no longer be an issue.  I'm closing the issue for now, but please re-open if it is still a problem.
