### ISSUE TITLE
populus init does not create a project.json

### ISSUE THREAD

**Issue by PJUllrich** [ethereum/populus#452]
* Populus Version: 2.2.0
* OS: linux
* Python Version: Python 3.6.4

### What was wrong?

`populus init` does not create a `project.json` file like explained [in the docs](http://populus.readthedocs.io/en/latest/config.html#introduction)

Instead, it creates only a default configuration in the `site-packages/populus/assets` folder of the virtual environment.

Here is the output of running `populus init` in an empty directory with virtual environment activated:
```
(venv) name@name-pc:~/test$ populus init
Wrote default populus configuration to `PATH_TO_VENV/venv/lib/python3.5/site-packages/populus/assets/defaults.v8.config.json`.
Created Directory: ./contracts
Created Example Contract: ./contracts/Greeter.sol
Created Directory: ./tests
Created Example Tests: ./tests/test_greeter.py
``` 

I expected it to create a `project.json` file like explained in the documentation. Is this desired behavior? If yes, I could update the project documentation. If no, any idea what's going wrong here?

#### Cute Animal Picture

![](https://media.giphy.com/media/JglVCaB0axZ4Y/giphy.gif)

**Comment by mandarvaze** [comment]
I think it is a known issue. "workaround" suggested [here](https://github.com/ethereum/populus/issues/414#issuecomment-352628648) i.e. "copy the 'defaults.v8.config.json' into your project root and rename to project.json "

**Comment by PJUllrich** [comment]
#414

**Comment by arpi9211** [comment]
Populus Version: 2.2.0
OS: osx

**Problem**:
FileNotFoundError: No populus project found for testing in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/populus/plugin.py:60

**Solution**:
when we run $ populus init command it will Wrote default populus configuration file at this location /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/populus/assets/defaults.v8.config.json

copy defaults.v8.config.json file and paste it on your project and rename defaults.v8.config.json to project.json file. This solution solved the issue for me
