### ISSUE TITLE
emit keyword: ParserError.

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/populus#454]
* Populus Version: populus==1.9.1
* OS: osx/linux

When I you `event` keyword on my smart contract I face with following error: When I remove `emit` keyword it works fine.

```
E               SolcError: contracts/eBlocBroker.sol:181:13: ParserError: Expected token Semicolon got 'LParen'
E               	emit LogJob(clusterAddr);
E               	           ^
E
E                       > command: `solc --standard-json`
E                       > return code: `0`
E                       > stderr:
E                       {"contracts":{},"errors":[{"component":"general","formattedMessage":"contracts/eBlocBroker.sol:181:13: ParserError: Expected token Semicolon got 'LParen'\n\temit LogJob(clusterAddr, jobKey, cluster.jobStatus[jobKey].length-1, storageType, miniLockID, jobDesc);\n\t           ^\n","message":"Expected token Semicolon got 'LParen'","severity":"error","type":"ParserError"}],"sources":{}}
E
E                       > stdout:

/usr/local/lib/python2.7/dist-packages/solc/main.py:
```

![maxresdefault](https://user-images.githubusercontent.com/18537398/37904113-513cffa4-3103-11e8-97f5-26b8d6c57bbc.jpg)

**Comment by pipermerriam** [comment]
That is an error from the solidity compiler and doesn't have to do with populus.  Check that the version of solidity that you have installed supports `emit` (I suspect that's a new language feature and you're installed version doesn't support it).

**Comment by elie222** [comment]
`emit` was added in Solidity 0.4.21.

**Comment by dangell7** [comment]
Also, I would highly recomend using this repo! I checks your solidity code. Not sure if it will find this error, but its a test you should run on all your contracts. 

https://github.com/duaraghav8/Solium

**Comment by avatar-lavventura** [comment]
Can I use `Populus` with solidity version `v0.4.21` ? @elie222
