### ISSUE TITLE
installation fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by paulperegud** [ethereum/populus#458]
* Populus Version: v2.2.0
* OS: linux

### What was wrong?

Populus relies on ethereum==1.6.1 which uses old version of secp256k1, which is incompatible with libssl1.1, shipped by default with Ubuntu 18.04. Possible solution - switching to ethereum>=2.0.0.

While compiling secp256k1 wheel, following error pops up:
```
    /tmp/pip-install-381pe6bt/secp256k1/libsecp256k1/src/tests.c:3702:52: error: dereferencing pointer to incomplete type ‘ECDSA_SIG {aka struct ECDSA_SIG_st}’
             valid_openssl = !BN_is_negative(sig_openssl->r) && !BN_is_negative(sig_openssl->s) && BN_num_bits(sig_openssl->r) > 0 && BN_num_bits(sig_openssl->r) <= 256 && BN_num_bits(sig_openssl->s) > 0 && BN_num_bits(sig_openssl->s) <= 256;

```
#### Cute Animal Picture

![cute_full](https://user-images.githubusercontent.com/247162/39131443-f1d46004-46fe-11e8-8c1b-440828b2dce3.jpg)

**Comment by mandarvaze** [comment]
It seems to be indirect dependency

```shell
Collecting ethereum<2.0.0,>=1.6.1 (from eth-testrpc>=1.3.0->populus)
```

So may be this issue belongs to `eth-testrpc` ?

**Comment by stfairy** [comment]
Try my workaround in https://github.com/ludbb/secp256k1-py/issues/24#issuecomment-397505150

**Comment by Netherdrake** [comment]
Why is this issue not being addressed?

**Comment by kkom** [comment]
@voith thanks so much for fixing it! do you have an ETA for merging your PR into master? i see that it was approved 2 weeks ago

**Comment by voith** [comment]
@kkom I'll try to get these merged by end of this week. I have to add documentation before we can make a release. If everything goes we should have a release by end of next week.

**Comment by voith** [comment]
#474 has landed. This issue should now be resolved. Will re-open if there's a problem persists.

**Comment by voith** [comment]
Please install populus from master untill a release is made.

**Comment by umrashrf** [comment]
```sudo apt-get install libsecp256k1-dev``` fixed it for me.
