### ISSUE TITLE
populus raises BytecodeMismatch

### ISSUE THREAD

**Issue by voith** [ethereum/populus#462]
* Populus Version: on master
* OS: osx
* solidity version: 0.4.24

### What was wrong?
Here's an MWE to replicate the issue

`project/contracts/SafeMath.sol`
```
pragma solidity ^0.4.18;
library SafeMath {

  function mul(uint256 a, uint256 b) internal pure returns (uint256) {
    if (a == 0) {
      return 0;
    }
    uint256 c = a * b;
    assert(c / a == b);
    return c;
  }

  function div(uint256 a, uint256 b) internal pure returns (uint256) {
    // assert(b > 0); // Solidity automatically throws when dividing by 0
    uint256 c = a / b;
    // assert(a == b * c + a % b); // There is no case in which this doesn't hold
    return c;
  }

  function sub(uint256 a, uint256 b) internal pure returns (uint256) {
    assert(b <= a);
    return a - b;
  }

  function add(uint256 a, uint256 b) internal pure returns (uint256) {
    uint256 c = a + b;
    assert(c >= a);
    return c;
  }
}

```
```python
In [1]: from populus import Project

In [2]: project = Project()

In [3]: with project.get_chain('tester') as chain:
   ...:     chain.provider.deploy_contract('SafeMath')
~/Python-Env/ico/lib/python3.5/site-packages/populus/contracts/provider.py in deploy_contract(self, contract_identifier, deploy_transaction, deploy_args, deploy_kwargs)
    128         self.registrar.set_contract_address(contract_identifier, contract_address)
    129
--> 130         return self.get_contract(contract_identifier), deploy_transaction_hash
    131
    132     def get_or_deploy_contract(self,

~/Python-Env/ico/lib/python3.5/site-packages/populus/contracts/provider.py in get_contract(self, contract_identifier)
     97         )
     98         if not bytecode_matched_addresses:
---> 99             raise BytecodeMismatch("None of the known addresses matched the expected bytecode")
    100         else:
    101             # TODO: don't just default to the first address.

BytecodeMismatch: None of the known addresses matched the expected bytecode
```
### Diagnosis
Below is the bytecode_runtime vs the code deployed.
Clearly they do not match.  However,  They match if the first 42  digits are ignored in both.
```
(Pdb) cls.bytecode_runtime
'0x73000000000000000000000000000000000000000030146080604052600080fd00a165627a7a72305820f1da76d729a168e6c424a57dd274d60ed04b6151270afd2dbcb1278079fa5e6f0029'
(Pdb) cls.web3.eth.getCode('0xc305c901078781C232A2a521C2aF7980f8385ee9')
'0x73c305c901078781c232a2a521c2af7980f8385ee930146080604052600080fd00a165627a7a72305820f1da76d729a168e6c424a57dd274d60ed04b6151270afd2dbcb1278079fa5e6f0029'
```
 It seems like the [compare_bytecode](https://github.com/ethereum/populus/blob/c256cbac0e343a1ce477a2e6128ef6a6c77b8c3c/populus/utils/contracts.py#L144-L168) might be a little outdated for the latest  solidity version

Also worth looking into https://github.com/ConsenSys/bytecode-verifier.

**Comment by voith** [comment]
cc @pipermerriam

**Comment by miohtama** [comment]
My assumption is that this is related to Swarm headers and metadata. Does Web 4.0 offer compile and related tools, so we could backport some of the utilities from there?

**Comment by voith** [comment]
@miohtama From reading `bytecode-verifier`'s code I can see that different solidity versions have different ways of matching `bytecode_runtime` with the code deployed on the blockchain.   Have a  look at [this line](https://github.com/ConsenSys/bytecode-verifier/blob/master/src/verifier.js#L113)
>My assumption is that this is related to Swarm headers and metadata

You are correct. I can verify from [this code](https://github.com/ConsenSys/bytecode-verifier/blob/4fdf06187926187a157b2d33b827a27bf9ca388c/src/verifier.js#L87-L93). However, looks like the newer versions have some changes which do not conform with the existing checks.

> Does Web 4.0 offer compile and related tools, so we could backport some of the utilities from there?

Do you mean web3 v4.0? If you're talking about web3 than web3 doesn't have any utilities for compiling. web3 works with the assumption that `abi` and `bytecode` will be provided by the user.

**Comment by voith** [comment]
@pipermerriam I got my code working by bypassing `compare_bytecode`. What is the design rationale behind having a check for comparing bytecode?

**Comment by pipermerriam** [comment]
So, bytecode comparison is not absolutely *required*.  I think the minimal check we do **need** is to ensure that the bytecode isn't empty.  Given the uncertainty of what comes next for the library, if you need this to get things working 👍

**Comment by voith** [comment]
I decided to find out what was going wrong in `compare_bytecode`. I compiled a simple smart contract against different versions of solidity. I noticed some differences in bytecodes for solidty version < 0.4.20 and >=0.4.20. Here are some results:
 ##### for solidity version 0.4.19
```python
In [6]: con['bin-runtime'] # expected_bytecode
Out[6]: '6060604052600080fd00a165627a7a72305820fe198797cf091375d4191836566e817de267342d7cfea15c50d3dc6ed958e91e0029'
# fast forward some steps of contract deployment
In [17]: w3.eth.getCode('0xbfBc3f7D8C0cF90E553Fc93ec95beE2d7104e7cd').hex() # deployed bytecode
Out[17]: '0x6060604052600080fd00a165627a7a72305820fe198797cf091375d4191836566e817de267342d7cfea15c50d3dc6ed958e91e0029'
```

 ##### for solidity version 0.4.20
```python
In [30]: con['bin-runtime']
Out[30]: '73000000000000000000000000000000000000000030146060604052600080fd00a165627a7a72305820917938062ffe211194022a5ffe160a7e99ba4e03a77b32685732efe661b16da90029'

In [36]: w3.eth.getCode('0x6dC65c405cF4053d9Adf018FD0eb7Ad52491bDb8').hex()
Out[36]: '0x736dc65c405cf4053d9adf018fd0eb7ad52491bdb830146060604052600080fd00a165627a7a72305820917938062ffe211194022a5ffe160a7e99ba4e03a77b32685732efe661b16da90029'
```
if you notice  carefully v0.4.20 has 46 extra hexadecimal digits compared to v0.4.19.
In fact, the first 46 digits in v0.4.20 have the  following format `r'73[0-9a-zA-Z]{40}3014'` and 
40 digits between 73 and 3014 happen to be the address at which they are deployed.

Also, the last 86 digits in both versions consist of the swarm hash. So, there's nothing wrong with the swarm hash. 

To be double sure about my debugging, I added v0.4.20 and 0.4.21 to CI. 
Here's the build: https://travis-ci.org/voith/populus/builds/405702207.
You can see the build pass for all versions of solidity except v0.4.20 and v0.4.22.

PS: I've checked this regex: `r'73[0-9a-zA-Z]{40}3014'` for several contracts, but I couldn't find much info about it in the solidity docs. However, the release notes of 0.4.20 say that significant changes have been made to optimize generated  bytecode.

**Comment by veox** [comment]
`r'73[0-9a-f]{40}3014'` is EVM bytecode for

```
PUSH20 <address>
ADDRESS
EQ
```

I.e., a comparison of a constant `<address>` (determined by the constructor at deployment time), with the actual address in the current execution context.

I think this relates to this change introduced in [`solc` v0.4.20](https://github.com/ethereum/solidity/releases/tag/v0.4.20):

> Code Generator: Prevent non-view functions in libraries from being called
directly (as opposed to via delegatecall).

**Comment by veox** [comment]
This is likely to stay part of `solc`, so Populus' `compare_bytecode` _could_ substitute the actual deployed address into the original runtime bytecode provided by `solc`; or something of this nature.

**Comment by voith** [comment]
>  r'73[0-9a-f]{40}3014' is EVM bytecode for

Great find @veox! From my quick read through the commit that you mentioned, it makes total sense.

> or it could ignore the bytes from 1 to 21 in the comparison, or something of this nature.

I was planning to use `re.sub`, i.e substitute with a placeholder if the pattern matches and then compare the bytecode. This way, the `compare_bytecode`  will be compatible with older versions of solidity too.
