### ISSUE TITLE
Drop support for python2.7

### ISSUE THREAD

**Issue by voith** [ethereum/populus#465]
* Populus Version: on  master
* OS: osx

### What was wrong?
https://medium.com/@pipermerriam/dropping-python-2-support-d781e7b48160 says that populus will drop support for  `python2.7`. Also `py-solc` dropped support for `python2.7` in https://github.com/ethereum/py-solc/pull/54. `py-solc` being a dependency of `populus`, the tests are failing as seen in #464

### How can it be fixed?
Quick fix: Drop `python2.7` tests from CI.
Long fix: Modify code to support python3 only syntax.

**Comment by voith** [comment]
cc @pipermerriam. Just need your opinion here. I will make the changes myself if we agree on a decision.

**Comment by veox** [comment]
All for this.

Do note that this is a change warranting a `MAJOR` version bump.

**Comment by carver** [comment]
:+1:

**Comment by cryptomental** [comment]
I opened a PR https://github.com/ethereum/populus/pull/466. fyi @carver @veox @pipermerriam .

**Comment by petri** [comment]
Given #466 is merged, this can be closed, right?

**Comment by voith** [comment]
yes, this can be closed now.

**Comment by veox** [comment]
Maybe it can stay open ;) as a reminder to bump the `MAJOR` version.

**Comment by veox** [comment]
Actually, you'll probably bump `MAJOR` anyway, considering all the other changes. (Up to @voith. ;))

**Comment by voith** [comment]
@veox Yeah, you're right. I have reserved the following weekend for populus to prepare master for `v3.0`. Don't really need this issue to be open as a reminder for a major `Bump`.
